{% set name = "neo4j-viz" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: db8a3f8fc35c5465ac2e4a971333b39377bb38d65a258f44185bf49010d08624
  patches:
    - patches/0001-avoid-strict-enum-tools-version.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  build:
    - msys2-patch  # [win]
  host:
    - python
    - pip
    - wheel
    - setuptools >=61.0.0
  run:
    - python
    - ipython >=7,<10
    - pydantic >=2,<3
    - pydantic-extra-types >=2,<3
    # avoided strict usage of enum tools
    - enum-tools >=0.12.0
  run_constrained:
    # pandas
    - pandas >=2,<3 
    - pandas-stubs >=2,<3
    # gds 
    - graphdatascience >=1,<2
    # notebook
    - ipykernel >=6.29.5
    - pykernel >=0.1.6
    - neo4j >=5.26.0
    - ipywidgets >=8.0.0
    - palettable >=3.3.3
    - matplotlib-base >=3.9.4
    - snowflake-snowpark-python >=1.37.0

# ModuleNotFoundError: No module named 'graphdatascience'
{% set tests_to_skip = "test_from_gds_mocked" %}
# Fixture 'gds' not found (part of graphdatascience pkg)
{% set tests_to_skip = tests_to_skip + " or test_from_neo4j_graph_basic" %}
{% set tests_to_skip = tests_to_skip + " or test_from_neo4j_result" %}
{% set tests_to_skip = tests_to_skip + " or test_from_neo4j_graph_full" %}
{% set tests_to_skip = tests_to_skip + " or test_from_gds_integration" %}
{% set tests_to_skip = tests_to_skip + " or test_from_gds_node_errors" %}
{% set tests_to_skip = tests_to_skip + " or test_from_gds_sample" %}
{% set tests_to_skip = tests_to_skip + " or test_from_gds_hetero" %}
# fixture 'neo4j_session' not found
{% set tests_to_skip = tests_to_skip + " or test_from_neo4j_graph_driver" %}
{% set tests_to_skip = tests_to_skip + " or test_from_neo4j_graph_row_limit_warning" %}
{% set tests_to_skip = tests_to_skip + " or test_from_neo4j_rel_error" %}
{% set tests_to_skip = tests_to_skip + " or test_from_neo4j_node_error" %}
# Missing test dir
{% set ignore_tests = " --ignore=tests/test_notebooks.py" %}
# selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome;
# Disabled the test that needs to use UI features.
{% set ignore_tests = ignore_tests + " --ignore=tests/test_render.py" %}
# ImportError: cannot import name 'VectorType' from 'snowflake.snowpark.types
{% set ignore_tests = ignore_tests + " --ignore=tests/test_snowflake.py" %}

test:
  source_files:
    - tests
  imports:
    - neo4j_viz
    - neo4j_viz.colors
    - neo4j_viz.gql_create
    - neo4j_viz.neo4j
    - neo4j_viz.node
    - neo4j_viz.node_size
    - neo4j_viz.nvl
    - neo4j_viz.options
    - neo4j_viz.pandas
    - neo4j_viz.relationship
    - neo4j_viz.visualization_graph
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v -k "not ({{ tests_to_skip }})" {{ ignore_tests }} tests
  requires:
    - pip
    - pytest >=8.3.4
    - neo4j >=5.26.0
    - selenium
    - pandas >=2,<3 
    - nbformat
    - pytest-mock >=3.14.0
    - nbclient
    - nbconvert >=7.16.6
    - palettable >=3.3.3
    - snowflake-snowpark-python >=1.37.0

about:
  home: https://neo4j.com
  summary: A simple graph visualization tool
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  description: A simple graph visualization tool
  dev_url: https://github.com/neo4j/python-graph-visualization/tree/main/python-wrapper
  doc_url: https://neo4j.com/docs/nvl-python/preview

extra:
  recipe-maintainers:
    - snegireff
